version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.04.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:FVO9d8IltmL/5RIRNgwO9Zicodrxq8M5ZfosG3UuYt4"
      - run:
          name: Release
          command: |
#            awk 'BEGIN{FS=OFS="\""} /version = "1.0.*"/ {split($2, arr, "."); arr[3]++; $2=arr[1]"."arr[2]"."arr[3]"-SNAPSHOT"} 1' sdk/build.gradle.kts > temp_file && mv temp_file sdk/build.gradle.kts
#            echo "Committing back to Github"
#            git config --global user.email "andressbryce@gmail.com"
#            git config --global user.name "Presage Tech Git Bot"
#            git add sdk/build.gradle.kts
#            git commit -m "Update Version [skip ci]"
#            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
#            git pull
#            git push
            echo $KEYSTORE | base64 -d > sdk/presagetech.gpg
            pwd
            ls -latr sdk/
            echo "$GPG_SIGNING_KEY" | base64 --decode | gpg --pinentry-mode loopback --passphrase $(echo $GPG_PASSWORD | base64 -d) --import
            gpg --list-secret-keys admins@presagetech.com
            mkdir -p ~/.gradle
            echo "signing.keyId=C88C6A20" > ~/.gradle/gradle.properties
            echo "signing.password=$(echo $GPG_PASSWORD | base64 -d)" >> ~/.gradle/gradle.properties
            echo "signing.secretKeyRingFile=presagetech.gpg" >> ~/.gradle/gradle.properties
            cat ~/.gradle/gradle.properties
      - run:
          name: Build and publish
          command: ./gradlew publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main