name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Update sdk/build.gradle.kts
      run: |
        sed -ri 's/(.*version = )([0-9]+)(.*)-SNAPSHOT/echo "\1$((\2+1))\3-SNAPSHOT"/ge' sdk/build.gradle.kts

    - name: Amend the last commit
      run: |
        git config --global user.email "gitbot@presagetech.com"
        git config --global user.name "Presage Tech Git Bot"
        git commit -a --amend --no-edit
        git push --force-with-lease
        echo "Complete"

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Build with Gradle
      run: ./gradlew publish
