name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Send it
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        KEYSTORE: ${{ secrets.KEYSTORE }}
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      run: |
        echo $KEYSTORE | base64 -d > sdk/presagetech.gpg
        pwd
        ls -latr sdk/
        gpg --pinentry-mode loopback --passphrase "$GPG_PASSWORD" --import <(echo "$GPG_SIGNING_KEY" | base64 --decode)
        gpg --list-secret-keys admins@presagetech.com
        mkdir -p ~/.gradle
        echo signing.keyId=C88C6A20 > ~/.gradle/gradle.properties
        echo signing.password=$GPG_PASSWORD >> ~/.gradle/gradle.properties
        echo signing.secretKeyRingFile=presagetech.gpg >> ~/.gradle/gradle.properties
        cat ~/.gradle/gradle.properties
        ./gradlew clean
        ./gradlew publish

        #- name: Update sdk/build.gradle.kts
        #run: |
        #set -e
        #awk 'BEGIN{FS=OFS="\""} /version = "1.0.*"/ {split($2, arr, "."); arr[3]++; $2=arr[1]"."arr[2]"."arr[3]"-SNAPSHOT"} 1' sdk/build.gradle.kts > temp_file && mv temp_file sdk/build.gradle.kts
        #
        #- name: Amend the last commit
        #run: |
        #git config --global user.email "gitbot@presagetech.com"
        #git config --global user.name "Presage Tech Git Bot"
        #git add sdk/build.gradle.kts
        #git commit -m "Update Version"
        #git push
        #echo "Complete"
